In [212]:
import pandas as pd
import csv 
import sqlite3
from geopy.geocoders import OpenCage
import requests
import re

In [213]:
nobel_data = "Resources/nobel_latest.csv"

In [214]:
nobel_df = pd.read_csv(nobel_data)
nobel_df

,Year,Laureate_Id,Firstname,Lastname,Category,Gender,Prize_Share,Motivation,Birth_Date,Birth_Country,Birth_City,Birth_Country_Code,Death_Date,Death_Country,Death_City,Death_Country_Code,Organization_Name,Organization_City,Organization_Country
0,1901,1,Wilhelm Conrad,Röntgen,physics,male,1,"""in recognition of the extraordinary services ...",1845-03-27,Prussia (now Germany),Lennep (now Remscheid),DE,10/2/1923,Germany,Munich,DE,Munich University,Munich,Germany
1,1902,2,Hendrik A.,Lorentz,physics,male,2,"""in recognition of the extraordinary service t...",1853-07-18,the Netherlands,Arnhem,NL,4/2/1928,the Netherlands,NaN,NL,Leiden University,Leiden,the Netherlands
2,1902,3,Pieter,Zeeman,physics,male,2,"""in recognition of the extraordinary service t...",1865-05-25,the Netherlands,Zonnemaire,NL,9/10/1943,the Netherlands,Amsterdam,NL,Amsterdam University,Amsterdam,the Netherlands
3,1903,4,Henri,Becquerel,physics,male,2,"""in recognition of the extraordinary services ...",1852-12-15,France,Paris,FR,25-08-1908,France,NaN,FR,École Polytechnique,Paris,France
4,1903,5,Pierre,Curie,physics,male,4,"""in recognition of the extraordinary services ...",1859-05-15,France,Paris,FR,19-04-1906,France,Paris,FR,École municipale de physique et de chimie indu...,Paris,France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,2022,1019,Memorial,NaN,peace,org,3,"""The Peace Prize laureates represent civil soc...",1987-00-00,NaN,NaN,NaN,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN
985,2022,1020,Center for Civil Liberties,NaN,peace,org,3,"""The Peace Prize laureates represent civil soc...",2007-00-00,NaN,NaN,NaN,0000-00-00,NaN,NaN,NaN,NaN,NaN,NaN
986,2022,1021,Ben,Bernanke,economics,male,3,"""for research on banks and financial crises""",13-12-1953,USA,Augusta GA,US,0000-00-00,NaN,NaN,NaN,The Brookings Institution,Washington D.C.,USA
987,2022,1022,Douglas,Diamond,economics,male,3,"""for research on banks and financial crises""",25-10-1953,USA,Chicago IL,US,0000-00-00,NaN,NaN,NaN,University of Chicago,Chicago IL,USA
988,2022,1023,Philip,Dybvig,economics,male,3,"""for research on banks and financial crises""",22-05-1955,USA,Gainesville FL,US,0000-00-00,NaN,NaN,NaN,Washington University,St. Louis MO,USA

In [215]:
cleaned_nobel_df = nobel_df.drop(["Prize_Share", "Birth_Country_Code", "Death_Country", "Death_City", "Death_Country_Code",
               "Organization_Name", "Organization_City", "Organization_Country"], axis = 1)

In [216]:
cleaned_nobel_df['Year'] = cleaned_nobel_df['Year'].astype('Int64')
cleaned_nobel_df['Laureate_Id'] = cleaned_nobel_df['Laureate_Id'].astype(str)
cleaned_nobel_df["Name"] = cleaned_nobel_df["Firstname"].astype(str)+ " " + cleaned_nobel_df["Lastname"].astype(str)
cleaned_nobel_df["Birth_Country"] = cleaned_nobel_df["Birth_Country"].astype(str)
cleaned_nobel_df["Birth_City"] = cleaned_nobel_df["Birth_City"].astype(str)

In [217]:
column_to_move = cleaned_nobel_df.pop("Name")

cleaned_nobel_df.insert(2, "Name", column_to_move)

In [218]:
full_name_df = cleaned_nobel_df.drop(["Firstname", "Lastname"], axis= 1)

In [219]:
full_name_df.head(140)

,Year,Laureate_Id,Name,Category,Gender,Motivation,Birth_Date,Birth_Country,Birth_City,Death_Date
0,1901,1,Wilhelm Conrad Röntgen,physics,male,"""in recognition of the extraordinary services ...",1845-03-27,Prussia (now Germany),Lennep (now Remscheid),10/2/1923
1,1902,2,Hendrik A. Lorentz,physics,male,"""in recognition of the extraordinary service t...",1853-07-18,the Netherlands,Arnhem,4/2/1928
2,1902,3,Pieter Zeeman,physics,male,"""in recognition of the extraordinary service t...",1865-05-25,the Netherlands,Zonnemaire,9/10/1943
3,1903,4,Henri Becquerel,physics,male,"""in recognition of the extraordinary services ...",1852-12-15,France,Paris,25-08-1908
4,1903,5,Pierre Curie,physics,male,"""in recognition of the extraordinary services ...",1859-05-15,France,Paris,19-04-1906
...,...,...,...,...,...,...,...,...,...,...
135,1989,136,Hans G. Dehmelt,physics,male,"""for the development of the ion trap technique""",9/9/1922,Prussia (now Germany),Görlitz,7/3/2017
136,1989,137,Wolfgang Paul,physics,male,"""for the development of the ion trap technique""",10/8/1913,Germany,Lorenzkirch,7/12/1993
137,1990,138,Jerome I. Friedman,physics,male,"""for their pioneering investigations concernin...",28-03-1930,USA,Chicago IL,0000-00-00
138,1990,139,Henry W. Kendall,physics,male,"""for their pioneering investigations concernin...",9/12/1926,USA,Boston MA,15-02-1999
139,1990,140,Richard E. Taylor,physics,male,"""for their pioneering investigations concernin...",2/11/1929,Canada,Medicine Hat Alberta,22-02-2018

In [220]:
def clean_country_name(place):
    # Find the text inside parentheses
    match = re.search(r'\(([^()]+)\)', place)
    
    if match:
        # Split the text inside parentheses and extract the last word
        words = match.group(1).split()
        if len(words) >= 2:
            country_name = words[-1]
        else:
            country_name = place
    else:
        country_name = place
    
    return country_name

# Apply the function to clean the column
full_name_df['Birth_Country'] = full_name_df['Birth_Country'].apply(clean_country_name)
full_name_df['Birth_City'] = full_name_df['Birth_City'].apply(clean_country_name)

In [221]:
full_name_df['Birth_Country'] = full_name_df['Birth_Country'].replace('USA', 'United States')
full_name_df['Birth_Country'] = full_name_df['Birth_Country'].replace('the Netherlands', 'Netherlands')
full_name_df['Birth_Country'] = full_name_df['Birth_Country'].replace('Canada', 'Canada')

In [222]:
# Mapping dictionary of state abbreviations to full names
state_mapping = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Deleware',
    'DC': 'District of Columbia',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennesee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'VI': 'Virgin Islands',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconson',
    'WY': 'Wyoming'
    }

# Loop through the cities column in your DataFrame
for i, city in enumerate(full_name_df['Birth_City']):
    # Split the city string into city name and state abbreviation
    city_parts = city.split(' ')
    if len(city_parts) == 2:
        city_name, state_abbr = city_parts
        # Check if the state abbreviation exists in the mapping dictionary
        if state_abbr in state_mapping:
            # Replace the state abbreviation with the full state name
            full_name_df.loc[i, 'Birth_City'] = f"{city_name}, {state_mapping[state_abbr]}"

\

In [223]:
def get_coordinates_from_wikipedia(page_title):
    base_url = 'https://en.wikipedia.org/w/api.php'
    params = {
        'action': 'query',
        'format': 'json',
        'prop': 'coordinates|info',
        'titles': page_title
    }

    response = requests.get(base_url, params=params)
    data = response.json()
    # Extract the coordinates and URL from the response
    pages = data['query']['pages']
    page_id = next(iter(pages))
    page_data = pages[page_id]
    coordinates = page_data.get('coordinates', [])
    url = page_data.get('fullurl')

    latitude = coordinates[0]['lat'] if coordinates else None
    longitude = coordinates[0]['lon'] if coordinates else None

    return latitude, longitude, url

# Initialize empty lists for coordinates and URLs
coordinates = []
wiki_urls = []

# Loop over the rows in the DataFrame
for row in full_name_df.itertuples(index=False):
    city = row.Birth_City
    country = row.Birth_Country
    name = row.Name

    # Replace spaces with underscores in the city and country names
    page_title_city = city.replace(' ', '_')
    page_title_country = country.replace(' ', '_')
    page_title_name = name.replace(' ', '_')
    
    # Get coordinates based on the birth city
    latitude, longitude, _ = get_coordinates_from_wikipedia(page_title_city)
    if latitude is None or longitude is None:
        # If coordinates are not found for the birth city, get coordinates based on the birth country
        latitude, longitude, _ = get_coordinates_from_wikipedia(page_title_country)

    url = f'https://en.wikipedia.org/wiki/{page_title_name}'

    coordinates.append((latitude, longitude))
    wiki_urls.append(url)

# Add the coordinates and URLs to the existing DataFrame
full_name_df['Coordinates'] = coordinates
full_name_df['Wikipedia_URL'] = wiki_urls

# Print the updated DataFrame
print(full_name_df)

     Year Laureate_Id                            Name   Category Gender  \
0    1901           1          Wilhelm Conrad Röntgen    physics   male
1    1902           2              Hendrik A. Lorentz    physics   male
2    1902           3                   Pieter Zeeman    physics   male
3    1903           4                 Henri Becquerel    physics   male
4    1903           5                    Pierre Curie    physics   male
..    ...         ...                             ...        ...    ...
984  2022        1019                    Memorial nan      peace    org
985  2022        1020  Center for Civil Liberties nan      peace    org
986  2022        1021                    Ben Bernanke  economics   male
987  2022        1022                 Douglas Diamond  economics   male
988  2022        1023                   Philip Dybvig  economics   male

                                            Motivation  Birth_Date  \
0    "in recognition of the extraordinary services ...  1845-03-27
1    "in recognition of the extraordinary service t...  1853-07-18
2    "in recognition of the extraordinary service t...  1865-05-25
3    "in recognition of the extraordinary services ...  1852-12-15
4    "in recognition of the extraordinary services ...  1859-05-15
..                                                 ...         ...
984  "The Peace Prize laureates represent civil soc...  1987-00-00
985  "The Peace Prize laureates represent civil soc...  2007-00-00
986       "for research on banks and financial crises"  13-12-1953
987       "for research on banks and financial crises"  25-10-1953
988       "for research on banks and financial crises"  22-05-1955

     Birth_Country            Birth_City  Death_Date  \
0          Germany             Remscheid   10/2/1923
1      Netherlands                Arnhem    4/2/1928
2      Netherlands            Zonnemaire   9/10/1943
3           France                 Paris  25-08-1908
4           France                 Paris  19-04-1906
..             ...                   ...         ...
984            nan                   nan  0000-00-00
985            nan                   nan  0000-00-00
986  United States      Augusta, Georgia  0000-00-00
987  United States     Chicago, Illinois  0000-00-00
988  United States  Gainesville, Florida  0000-00-00

                     Coordinates  \
0             (51.18333333, 7.2)
1      (51.98333333, 5.91666667)
2          (51.7125, 3.95083333)
3      (48.85666667, 2.35222222)
4      (48.85666667, 2.35222222)
..                           ...
984                 (None, None)
985                 (None, None)
986             (33.47, -81.975)
987                   (40, -100)
988  (29.65199722, -82.32499167)

                                         Wikipedia_URL
0    https://en.wikipedia.org/wiki/Wilhelm_Conrad_R...
1     https://en.wikipedia.org/wiki/Hendrik_A._Lorentz
2          https://en.wikipedia.org/wiki/Pieter_Zeeman
3        https://en.wikipedia.org/wiki/Henri_Becquerel
4           https://en.wikipedia.org/wiki/Pierre_Curie
..                                                 ...
984         https://en.wikipedia.org/wiki/Memorial_nan
985  https://en.wikipedia.org/wiki/Center_for_Civil...
986         https://en.wikipedia.org/wiki/Ben_Bernanke
987      https://en.wikipedia.org/wiki/Douglas_Diamond
988        https://en.wikipedia.org/wiki/Philip_Dybvig

[989 rows x 12 columns]

In [226]:
full_name_df.head(50)

,Year,Laureate_Id,Name,Category,Gender,Motivation,Birth_Date,Birth_Country,Birth_City,Death_Date,Coordinates,Wikipedia_URL
0,1901,1,Wilhelm Conrad Röntgen,physics,male,"""in recognition of the extraordinary services ...",1845-03-27,Germany,Remscheid,10/2/1923,"(51.18333333, 7.2)",https://en.wikipedia.org/wiki/Wilhelm_Conrad_R...
1,1902,2,Hendrik A. Lorentz,physics,male,"""in recognition of the extraordinary service t...",1853-07-18,Netherlands,Arnhem,4/2/1928,"(51.98333333, 5.91666667)",https://en.wikipedia.org/wiki/Hendrik_A._Lorentz
2,1902,3,Pieter Zeeman,physics,male,"""in recognition of the extraordinary service t...",1865-05-25,Netherlands,Zonnemaire,9/10/1943,"(51.7125, 3.95083333)",https://en.wikipedia.org/wiki/Pieter_Zeeman
3,1903,4,Henri Becquerel,physics,male,"""in recognition of the extraordinary services ...",1852-12-15,France,Paris,25-08-1908,"(48.85666667, 2.35222222)",https://en.wikipedia.org/wiki/Henri_Becquerel
4,1903,5,Pierre Curie,physics,male,"""in recognition of the extraordinary services ...",1859-05-15,France,Paris,19-04-1906,"(48.85666667, 2.35222222)",https://en.wikipedia.org/wiki/Pierre_Curie
5,1903,6,Marie Curie,physics,female,"""in recognition of the extraordinary services ...",1867-11-07,Poland,Warsaw,4/7/1934,"(52.23, 21.01111111)",https://en.wikipedia.org/wiki/Marie_Curie
6,1911,6,Marie Curie,chemistry,female,"""in recognition of her services to the advance...",1867-11-07,Poland,Warsaw,4/7/1934,"(52.23, 21.01111111)",https://en.wikipedia.org/wiki/Marie_Curie
7,1904,8,Lord Rayleigh,physics,male,"""for his investigations of the densities of th...",1842-11-12,United Kingdom,Langford Grove Maldon Essex,30-06-1919,"(55, -3)",https://en.wikipedia.org/wiki/Lord_Rayleigh
8,1905,9,Philipp Lenard,physics,male,"""for his work on cathode rays""",1862-06-07,Slovakia,Bratislava,20-05-1947,"(48.14388889, 17.10972222)",https://en.wikipedia.org/wiki/Philipp_Lenard
9,1906,10,J.J. Thomson,physics,male,"""in recognition of the great merits of his the...",1856-12-18,United Kingdom,Cheetham Hill,30-08-1940,"(55, -3)",https://en.wikipedia.org/wiki/J.J._Thomson
10,1907,11,Albert A. Michelson,physics,male,"""for his optical precision instruments and the...",1852-12-19,Poland,Strzelno,9/5/1931,"(52.62944444, 18.17)",https://en.wikipedia.org/wiki/Albert_A._Michelson
11,1908,12,Gabriel Lippmann,physics,male,"""for his method of reproducing colours photogr...",1845-08-16,Luxembourg,Hollerich,13-07-1921,"(49.599, 6.12)",https://en.wikipedia.org/wiki/Gabriel_Lippmann
12,1909,13,Guglielmo Marconi,physics,male,"""in recognition of their contributions to the ...",1874-04-25,Italy,Bologna,20-07-1937,"(44.49388889, 11.34277778)",https://en.wikipedia.org/wiki/Guglielmo_Marconi
13,1909,14,Ferdinand Braun,physics,male,"""in recognition of their contributions to the ...",1850-06-06,Germany,Fulda,20-04-1918,"(50.55083333, 9.67527778)",https://en.wikipedia.org/wiki/Ferdinand_Braun
14,1910,15,Johannes Diderik van der Waals,physics,male,"""for his work on the equation of state for gas...",1837-11-23,Netherlands,Leiden,8/3/1923,"(52.16, 4.49)",https://en.wikipedia.org/wiki/Johannes_Diderik...
15,1911,16,Wilhelm Wien,physics,male,"""for his discoveries regarding the laws govern...",1864-01-13,Russia,Parusnoye,30-08-1928,"(66, 94)",https://en.wikipedia.org/wiki/Wilhelm_Wien
16,1912,17,Gustaf Dalén,physics,male,"""for his invention of automatic regulators for...",1869-11-30,Sweden,Stenstorp,9/12/1937,"(58.27444444, 13.71361111)",https://en.wikipedia.org/wiki/Gustaf_Dalén
17,1913,18,Heike Kamerlingh Onnes,physics,male,"""for his investigations on the properties of m...",1853-09-21,Netherlands,Groningen,21-02-1926,"(53.21888889, 6.5675)",https://en.wikipedia.org/wiki/Heike_Kamerlingh...
18,1914,19,Max von Laue,physics,male,"""for his discovery of the diffraction of X-ray...",1879-10-09,Germany,Pfaffendorf,23-04-1960,"(51, 9)",https://en.wikipedia.org/wiki/Max_von_Laue
19,1915,20,William Bragg,physics,male,"""for their services in the analysis of crystal...",1862-07-02,United Kingdom,Wigton,12/3/1942,"(54.823, -3.159)",https://en.wikipedia.org/wiki/William_Bragg
20,1915,21,Lawrence Bragg,physics,male,"""for their services in the analysis of crystal...",1890-03-31,Australia,Adelaide,1/7/1971,"(-34.9275, 138.6)",https://en.wikipedia.org/wiki/Lawrence_Bragg
21,1917,22,Charles Glover Barkla,physics,male,"""for his discovery of the characteristic R&oum...",1877-06-07,United Kingdom,Widnes,23-10-1944,"(53.363, -2.728)",https://en.wikipedia.org/wiki/Charles_Glover_B...
22,1918,23,Max Planck,physics,male,"""in recognition of the services he rendered to...",1858-04-23,Germany,Kiel,4/10/1947,"(54.32333333, 10.13944444)",https://en.wikipedia.org/wiki/Max_Planck
23,1919,24,Johannes Stark,physics,male,"""for his discovery of the Doppler effect in ca...",1874-04-15,Germany,Schickenhof,21-06-1957,"(51, 9)",https://en.wikipedia.org/wiki/Johannes_Stark
24,1920,25,Charles Edouard Guillaume,physics,male,"""in recognition of the service he has rendered...",1861-02-15,Switzerland,Fleurier,13-06-1938,"(46.9, 6.58333333)",https://en.wikipedia.org/wiki/Charles_Edouard_...
25,1921,26,Albert Einstein,physics,male,"""for his services to Theoretical Physics and e...",1879-03-14,Germany,Ulm,18-04-1955,"(48.4, 9.98333333)",https://en.wikipedia.org/wiki/Albert_Einstein
26,1922,27,Niels Bohr,physics,male,"""for his services in the investigation of the ...",1885-10-07,Denmark,Copenhagen,18-11-1962,"(55.67611111, 12.56833333)",https://en.wikipedia.org/wiki/Niels_Bohr
27,1923,28,Robert A. Millikan,physics,male,"""for his work on the elementary charge of elec...",1868-03-22,United States,"Morrison, Illinois",19-12-1953,"(41.80916667, -89.96805556)",https://en.wikipedia.org/wiki/Robert_A._Millikan
28,1924,29,Manne Siegbahn,physics,male,"""for his discoveries and research in the field...",1886-12-03,Sweden,Örebro,26-09-1978,"(59.27388889, 15.2075)",https://en.wikipedia.org/wiki/Manne_Siegbahn
29,1925,30,James Franck,physics,male,"""for their discovery of the laws governing the...",1882-08-26,Germany,Hamburg,21-05-1964,"(53.55, 10)",https://en.wikipedia.org/wiki/James_Franck
30,1925,31,Gustav Hertz,physics,male,"""for their discovery of the laws governing the...",1887-07-22,Germany,Hamburg,30-10-1975,"(53.55, 10)",https://en.wikipedia.org/wiki/Gustav_Hertz
31,1926,32,Jean Baptiste Perrin,physics,male,"""for his work on the discontinuous structure o...",1870-09-30,France,Lille,17-04-1942,"(50.6278, 3.0583)",https://en.wikipedia.org/wiki/Jean_Baptiste_Pe...
32,1927,33,Arthur H. Compton,physics,male,"""for his discovery of the effect named after him""",1892-09-10,United States,"Wooster, Ohio",15-03-1962,"(40.80916667, -81.93722222)",https://en.wikipedia.org/wiki/Arthur_H._Compton
33,1927,34,C.T.R. Wilson,physics,male,"""for his method of making the paths of electri...",1869-02-14,Scotland,Glencorse,15-11-1959,"(55.8507, -3.2042)",https://en.wikipedia.org/wiki/C.T.R._Wilson
34,1928,35,Owen Willans Richardson,physics,male,"""for his work on the thermionic phenomenon and...",1879-04-26,United Kingdom,Dewsbury,15-02-1959,"(53.691, -1.633)",https://en.wikipedia.org/wiki/Owen_Willans_Ric...
35,1929,36,Louis de Broglie,physics,male,"""for his discovery of the wave nature of elect...",1892-08-15,France,Dieppe,19-03-1987,"(49.925, 1.075)",https://en.wikipedia.org/wiki/Louis_de_Broglie
36,1930,37,Sir Chandrasekhara Venkata Raman,physics,male,"""for his work on the scattering of light and f...",1888-11-07,India,Tiruchirappalli,21-11-1970,"(10.79027778, 78.70472222)",https://en.wikipedia.org/wiki/Sir_Chandrasekha...
37,1932,38,Werner Heisenberg,physics,male,"""for the creation of quantum mechanics the app...",5/12/1901,Germany,Würzburg,1/2/1976,"(49.78333333, 9.93333333)",https://en.wikipedia.org/wiki/Werner_Heisenberg
38,1933,39,Erwin Schrödinger,physics,male,"""for the discovery of new productive forms of ...",1887-08-12,Austria,Vienna,4/1/1961,"(48.2, 16.36666667)",https://en.wikipedia.org/wiki/Erwin_Schrödinger
39,1933,40,Paul A.M. Dirac,physics,male,"""for the discovery of new productive forms of ...",8/8/1902,United Kingdom,Bristol,20-10-1984,"(51.45361111, -2.5975)",https://en.wikipedia.org/wiki/Paul_A.M._Dirac
40,1935,41,James Chadwick,physics,male,"""for the discovery of the neutron""",1891-10-20,United Kingdom,Manchester,24-07-1974,"(53.47944444, -2.24527778)",https://en.wikipedia.org/wiki/James_Chadwick
41,1936,42,Victor F. Hess,physics,male,"""for his discovery of cosmic radiation""",1883-06-24,Austria,Peggau,17-12-1964,"(47.20638889, 15.34416667)",https://en.wikipedia.org/wiki/Victor_F._Hess
42,1936,43,Carl D. Anderson,physics,male,"""for his discovery of the positron""",3/9/1905,United States,New York NY,11/1/1991,"(40, -100)",https://en.wikipedia.org/wiki/Carl_D._Anderson
43,1937,44,Clinton Davisson,physics,male,"""for their experimental discovery of the diffr...",1881-10-22,United States,"Bloomington, Illinois",1/2/1958,"(40.48416667, -88.99361111)",https://en.wikipedia.org/wiki/Clinton_Davisson
44,1937,45,George Paget Thomson,physics,male,"""for their experimental discovery of the diffr...",1892-05-03,United Kingdom,Cambridge,10/9/1975,"(52.20527778, 0.11916667)",https://en.wikipedia.org/wiki/George_Paget_Tho...
45,1938,46,Enrico Fermi,physics,male,"""for his demonstrations of the existence of ne...",29-09-1901,Italy,Rome,28-11-1954,"(41.89333333, 12.48277778)",https://en.wikipedia.org/wiki/Enrico_Fermi
46,1939,47,Ernest Lawrence,physics,male,"""for the invention and development of the cycl...",8/8/1901,United States,"Canton, South Dakota",27-08-1958,"(43.30222222, -96.59083333)",https://en.wikipedia.org/wiki/Ernest_Lawrence
47,1943,48,Otto Stern,physics,male,"""for his contribution to the development of th...",1888-02-17,Poland,Zory,17-08-1969,"(52, 20)",https://en.wikipedia.org/wiki/Otto_Stern
48,1944,49,Isidor Isaac Rabi,physics,male,"""for his resonance method for recording the ma...",1898-07-29,Poland,Rymanow,11/1/1988,"(52, 20)",https://en.wikipedia.org/wiki/Isidor_Isaac_Rabi
49,1945,50,Wolfgang Pauli,physics,male,"""for the discovery of the Exclusion Principle ...",25-04-1900,Austria,Vienna,15-12-1958,"(48.2, 16.36666667)",https://en.wikipedia.org/wiki/Wolfgang_Pauli

In [225]:
con = sqlite3.connect("data/nobel_prize.db")
curs = con.cursor()

curs.execute("DROP TABLE IF EXISTS nobel_winners")

curs.execute("""CREATE TABLE recipients (
    Year INTEGER,
    id INTEGER PRIMARY KEY,
    Laureate_Id,
    Name TEXT,
    Category TEXT,
    Gender TEXT,
    Motivation TEXT,
    Birth_Date TEXT,
    Birth_Country TEXT,
    Death_Date TEXT
    )
""")
full_name_df.to_sql("recipients", con, if_exists="append", index=False)

con.commit()
con.close()